---
- name: load docker image
  command: docker load -i /data/consul.tar

- name: start consul server container
  docker_container:
    restart_policy: always
    name: consul-server
    image: progrium/consul
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
    command: -server -advertise "{{ consul_master_ip }}" -bootstrap-expect 1
  tags:
    - consul-server
