---
- hosts: all
  become: yes
  roles:
    - common

- hosts: management
  gather_facts: no
  become: yes
  roles:
    - consul-server
    - swarm-manager

- hosts: workers
  become: yes
  serial: 1
  roles:
    - consul-client
    - swarm-client
    - registrator
    - image-update

- hosts: management
  become: yes
  roles:
    - app
