---
- name: docker compose
  docker_service:
    api_version: 1.24
    docker_url: "tcp://172.28.128.10:3375"
    project_name: NGINX
    state: present
    timeout: 360
    scale:
      web: 1
    definition:
      version: '2'
      services:
        web:
          image: nginx
  tags:
    - app-compose
