---
- name: load docker image
  command: docker load -i /data/consul.tar

- name: start consul clients
  docker_container:
    restart_policy: always
    name: consul-client
    image: progrium/consul
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
    command: -rejoin -advertise "{{ ansible_enp0s8.ipv4.address }}" -join "{{ consul_master_ip }}"
  tags:
    - consul-client
